# Generated by Django 3.1.6 on 2021-02-10 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
